version: '3'

services:
  mysql-master:
    image: mysql:8.0.30
    command: --server-id=1 --log-bin=mysql-bin --gtid-mode=ON --enforce-gtid-consistency=true
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db/mysql-master-data:/var/lib/mysql
      - ./config/mysql/master-my.cnf:/etc/mysql/conf.d/master-my.cnf
      - ./scripts/master-init.sql:/docker-entrypoint-initdb.d/master-init.sql
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-slave:
    image: mysql:8.0.30
    command: --server-id=2 --log-bin=mysql-bin --gtid-mode=ON --enforce-gtid-consistency=true
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      mysql-master:
        condition: service_healthy
    volumes:
      - ./db/mysql-slave-data:/var/lib/mysql
      - ./config/mysql/slave-my.cnf:/etc/mysql/conf.d/slave-my.cnf
      - ./scripts/slave-init.sql:/docker-entrypoint-initdb.d/slave-init.sql
    ports:
      - "14306:3306"

  redis:
    image: redis:latest
    volumes:
      - ./db/redis-data:/data
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    volumes:
      - ./db/mongodb-data:/data/db
    ports:
      - "27017:27017"
