spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:templates/
    suffix: .html

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # 단일 파일 최대 크기
      max-request-size: 25MB # 요청 전체 크기 제한
      # 해당 파일은 메모리에 저장됩니다. 그러나 파일이 이 크기를 초과하면 임시 파일이 디스크에 저장됩니다.
      # 이렇게 하면 작은 파일의 경우 디스크에 저장하지 않고 메모리에서 처리함으로써 더 빠른 처리 속도를 얻을 수 있습니다.
      file-size-threshold: 2KB # 임시 파일을 생성하기 전에 메모리에 저장되는 파일의 크기 제한

#  datasource:
#    url: jdbc:mysql:${MASTER_DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  master:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql:${MASTER_DB_URL}
        username: ${EASY_DB_USERNAME}
        password: ${EASY_DB_PASSWORD}
      hibernate:
        ddl-auto: update
  slave:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql:${SLAVE_DB_URL}
        username: ${EASY_DB_USERNAME}
        password: ${EASY_DB_PASSWORD}

  #    url: jdbc:h2:tcp://localhost/~/test
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password:

  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000 # 30 * 60 * 1000 == 30분 (30분안에 회원가입이 이뤄져야 한다.)

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://easy-api.sgmchain.net/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: https://easy-api.sgmchain.net/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://easy-api.sgmchain.net/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: 8640000
    refresh: 8640000

client:
  app:
    url: https://easy.sgmchain.net

cors:
  allow:
    url: https://easy.sgmchain.net

server:
  app:
    url: https://easy-api.sgmchain.net

upload:
  profile:
    directory: /easy/upload/profile