spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://39.116.170.25:13306/easy
    username: easy
    password: easy!@34
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1078837955974-7dqkjsd1u059agn1a6e2uh3cnm0nm98i.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://easy-api.sgmchain.net/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            client-id: EBqQxvvPsZodYPZZsHI4
            client-secret: msomB4NsKO
            redirect-uri: https://easy-api.sgmchain.net/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: b71f73392298c32482e6458aab4e6a26
            client-secret: 2Unay3rfVpStAWeKixsrK1lUIQg1VBpb
            redirect-uri: https://easy-api.sgmchain.net/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            client-authentication-method : POST
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: dfkgjdfgDHNSB75hjdvhanem7213742ASNDGCkSA7JDAKHFAKJSHFJSJHF123FASFBBFHAJDDHjasjfhfh87j4
  expiration:
    access: 86400000
    refresh: 86400000

client:
  app:
    url: https://easy.sgmchain.net
#    url: http://localhost:3000